from typing import Literal

from pydantic import BaseModel, Field


class PlannedQuery(BaseModel):
    """A single executable query generated by the planner."""

    query: str = Field(min_length=1, max_length=500)
    provider: Literal["searxng"] = "searxng"


class SearchPlan(BaseModel):
    """Structured search plan generated from a user's natural-language query."""

    intent: str = Field(min_length=1, max_length=100)
    objective: str = Field(min_length=1, max_length=500)
    entities: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    queries: list[PlannedQuery] = Field(min_length=1)
